#Configuraci贸n para ambiente de desarollo
spring:
  profiles: dev
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
      url: jdbc:mysql://localhost:3306/see_database
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
security:
  basic:
    enabled: false
server:
  port: 8383
sregistry: 
  protocol: http://
  host: localhost
  port: :10000
  context: /serviceRegistry/v1
  registerResource: /publishService    
     
---
#Configuraci贸n para ambiente de Pruebas
spring:
  profiles: test
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
      url: jdbc:mysql://localhost:3306/see_database
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
security:
  basic:
    enabled: false
server:
  port: 8383
sregistry: 
  protocol: http://
  host: localhost
  port: :10000
  context: /serviceRegistry/v1
  registerResource: /publishService   
#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework: ERROR
#    org.springframework.data: ERROR
#  file: see_test_log.log
    
---
 
#Configuraci贸n para ambiente de Producci贸n      
spring:
  profiles: prod
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
      url: jdbc:mysql://localhost:3306/see_database
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
security:
  basic:
    enabled: false
server:
  port: 8383
sregistry: 
  protocol: http://
  host: localhost
  port: :10000
  context: /serviceRegistry/v1
  registerResource: /publishService   